services:
  - type: web
    name: kaze-business-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kaze-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: kaze-db
    plan: free